<?php
defined( 'ABSPATH' ) || exit;

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'VK_AdnetworkAd' => $baseDir . '/classes/ad.php',
    'VK_Adnetwork' => $baseDir . '/public/class-vk-adnetwork.php',
    'VK_Adnetwork\\Placement_Type' => $baseDir . '/src/Placement_Type.php',
    'VK_Adnetwork\\Placement_Type_Options' => $baseDir . '/src/Placement_Type_Options.php',
    'VK_Adnetwork_Ad' => $baseDir . '/classes/ad.php',
    'VK_Adnetwork_Ad_Ajax_Callbacks' => $baseDir . '/classes/ad_ajax_callbacks.php',
    'VK_Adnetwork_Ad_Debug' => $baseDir . '/classes/ad-debug.php',
    'VK_Adnetwork_Ad_Expiration' => $baseDir . '/classes/ad-expiration.php',
    'VK_Adnetwork_Ad_Health_Notices' => $baseDir . '/classes/ad-health-notices.php',
    'VK_Adnetwork_Ad_List_Filters' => $baseDir . '/admin/includes/class-list-filters.php',
    'VK_Adnetwork_Ad_Type_Abstract' => $baseDir . '/classes/ad_type_abstract.php',
    'VK_Adnetwork_Ad_Type_Plain' => $baseDir . '/classes/ad_type_plain.php',
    'VK_Adnetwork_Admin' => $baseDir . '/admin/class-vk-adnetwork-admin.php',
    'VK_Adnetwork_Admin_Ad_Type' => $baseDir . '/admin/includes/class-ad-type.php',
    'VK_Adnetwork_Admin_Menu' => $baseDir . '/admin/includes/class-menu.php',
    'VK_Adnetwork_Admin_Meta_Boxes' => $baseDir . '/admin/includes/class-meta-box.php',
    'VK_Adnetwork_Admin_Notices' => $baseDir . '/admin/includes/class-notices.php',
    'VK_Adnetwork_Admin_Settings' => $baseDir . '/admin/includes/class-settings.php',
    'VK_Adnetwork_Admin_Upgrades' => $baseDir . '/admin/includes/class-admin-upgrades.php',
    'VK_Adnetwork_Ajax' => $baseDir . '/classes/ad-ajax.php',
    'VK_Adnetwork_Checks' => $baseDir . '/classes/checks.php',
    'VK_Adnetwork_Compatibility' => $baseDir . '/classes/compatibility.php',
    'VK_Adnetwork_Filesystem' => $baseDir . '/classes/filesystem.php',
    'VK_Adnetwork_Frontend_Checks' => $baseDir . '/classes/frontend_checks.php',
    'VK_Adnetwork_Frontend_Notices' => $baseDir . '/classes/frontend-notices.php',
    'VK_Adnetwork_In_Content_Injector' => $baseDir . '/classes/in-content-injector.php',
    'VK_Adnetwork_Inline_Css' => $baseDir . '/classes/inline-css.php',
    'VK_Adnetwork_Modal' => $baseDir . '/classes/VK_Adnetwork_Modal.php',
    'VK_Adnetwork_Model' => $baseDir . '/classes/ad-model.php',
    'VK_Adnetwork_Overview_Widgets_Callbacks' => $baseDir . '/admin/includes/class-overview-widgets.php',
    'VK_Adnetwork_Placements' => $baseDir . '/classes/ad_placements.php',
    'VK_Adnetwork_Plugin' => $baseDir . '/classes/plugin.php',
    'VK_Adnetwork_Select' => $baseDir . '/classes/ad-select.php',
    'VK_Adnetwork_Upgrades' => $baseDir . '/classes/upgrades.php',
    'VK_Adnetwork_Utils' => $baseDir . '/classes/utils.php',

    'VK_Adnetwork_Widget' => $baseDir . '/classes/widget.php',
);
