<?php

// autoload_real.php @generated by Composer

use VK_Adnetwork\Composer\Autoload\ClassLoader;
use VK_Adnetwork\Composer\Autoload\vk_adnetwork_ComposerStaticInit;

class vk_adnetwork_ComposerAutoloaderInit
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('VK_Adnetwork\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \VK_Adnetwork\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('vk_adnetwork_ComposerAutoloaderInit', 'loadClassLoader'), true, true);
        self::$loader = $loader = new ClassLoader(dirname(__DIR__));
        spl_autoload_unregister(array('vk_adnetwork_ComposerAutoloaderInit', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(vk_adnetwork_ComposerStaticInit::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
