<?php
defined( 'ABSPATH' ) || exit;

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = "Don't support autoloading on PHP < 5.6 and you are running ".PHP_VERSION.', please upgrade PHP. Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite
        } elseif (!headers_sent()) {
            echo esc_html($err);
        }
    }
    trigger_error(
        esc_html($err),
        E_USER_ERROR
    );
}

require_once __DIR__ . '/composer/autoload_real.php';

return vk_adnetwork_ComposerAutoloaderInit::getLoader();
